name: gentoo_update_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  crypto: ^3.0.3
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.6.5
  flutter_launcher_icons: ^0.13.1
  pointycastle: ^3.7.3
  convert: ^3.1.1
  cloud_functions: ^4.4.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/gentoo_logo.ico"

flutter_launcher_icons:
  android: true
  image_path: "assets/play_store_512.png"
